### ISSUE TITLE
The text column is insanely narrow

### ISSUE THREAD

**Issue by l29ah** [grishka/Smithereen#14]
While wasting most of the screen estate on empty space.
![screenshot-narrow](https://user-images.githubusercontent.com/31852/108162608-82006480-70fe-11eb-9681-86dd6daab410.png)

**Comment by grishka** [comment]
This is intentional, as I'm mostly copying an older version of VK layout. The initial design was wider with the same thinghts, but it turned out to be inconvenient to read lines of text that were this long.

This space will be used for other stuff later — there will be a big "up" button like in VK on the left, and (for logged in users) there might be something on the right. For example that pop-up friend list in case there will ever be messaging. There will also be pop-up notifications in the bottom left corner, again like in VK.
